    const Raças = [
      "HUMANO",
      "SUPER HUMANO",
      "ANÃO",
      "DEMI-HUMANO",
      "ELFO",
      "DRUIDA",
      "ANIMAL",
      "CBORG",
      "ANJO",
      "ANJO CAIDO",
      "DEMONIO",
      "VAMPIRO",
      "GOUL",
      "GIGANTE",
      "GOLEM",
      "FANTASMA",
      "SLIME",
      "ORC",
      "METAMORFO",
      "LOBISOMEM",
      "DRACONATO",
      "ONI",
      "CORROMPIDOS"
    ]