const Classes = [
  { name: "Esadachim", color: "#d08770" },
  { name: "Bardo", color: "#b48ead" },
  { name: "Juggernaut", color: "#a3be8c" },
  { name: "Paladino", color: "#ebcb8b" },
  { name: "Assassino", color: "#bf616a" },
  { name: "Clerigo", color: "#eceff4" },
  { name: "Tanke", color: "#d08770" },
  { name: "Mago", color: "#5e81ac" },
  { name: "Anti-mago", color: "#8fbcbb" },
  { name: "Domador", color: "#a3be8c" },
  { name: "Pistoleiro", color: "#d08770" },
  { name: "Lutador", color: "#ebcb8b" },
  { name: "Arqueiro", color: "#a3be8c" },
  { name: "Invocador", color: "#b48ead" },
  { name: "Sniper", color: "#5e81ac" },
  { name: "Executor", color: "#d74f4f" },
  { name: "Ninja", color: "#4c566a" },
  { name: "Caçador", color: "#a3be8c" },
  { name: "Lanceiro", color: "#88c0d0" },
  { name: "Ladino", color: "#ab7967" },
  { name: "Feiticeiro", color: "#b48ead" },
  { name: "Artifice", color: "#a1cfff" },
  { name: "Cavaleiro", color: "#eceff4" },
  { name: "Magico", color: "#81a1c1" },
  { name: "Ceifador", color: "#bf616a" },
  { name: "Guerreiro arcano", color: "#8fbcbb" }
];
