const Races = [
  { name: "Humano", color: "#ffffff" },
  { name: "Super humano", color: "#a3be8c" },
  { name: "Anão", color: "#d08770" },
  { name: "Demi-humano", color: "#b48ead" },
  { name: "Elfo", color: "#88c0d0" },
  { name: "Druida", color: "#8fbcbb" },
  { name: "Animal", color: "#ebcb8b" },
  { name: "Cborg", color: "#5e81ac" },
  { name: "Anjo", color: "#eceff4" },
  { name: "Anjo caido", color: "#bf616a" },
  { name: "Demonio", color: "#bf616a" },
  { name: "Vampiro", color: "#b48ead" },
  { name: "Goul", color: "#a3be8c" },
  { name: "Gigante", color: "#d08770" },
  { name: "Golem", color: "#7c6f64" },
  { name: "Fantasma", color: "#c0c0c0" },
  { name: "Slime", color: "#a1cfff" },
  { name: "Orc", color: "#a3be8c" },
  { name: "Metamorfo", color: "#ab7967" },
  { name: "Lobisomem", color: "#705749" },
  { name: "Draconato", color: "#d65d0e" },
  { name: "Oni", color: "#d74f4f" },
  { name: "Corrompidos", color: "#a40000" }
];
