    const Classes = [
      "ESADACHIM",
      "BARDO",
      "JUGGERNAUT",
      "PALADINO",
      "ASSASSINO",
      "CLERIGO",
      "TANKE",
      "MAGO",
      "ANTI-MAGO",
      "DOMADOR",
      "PISTOLEIRO",
      "LUTADOR",
      "ARQUEIRO",
      "INVOCADOR",
      "SNIPER",
      "EXECUTOR",
      "NINJA",
      "CAÇADOR",
      "LANCEIRO",
      "LADINO",
      "FEITICEIRO",
      "ARTIFICE",
      "CAVALEIRO",
      "MAGICO",
      "CEIFADOR",
      "GUERREIRO ARCANO"
    ]